---
- hosts: instance
  gather_facts: true
  become: yes
  vars_files:
    - vars.yaml
  roles:
    - nginxinc.nginx
  post_tasks:
    - name: Check if Website Folder Exists
      stat: 
        path: /usr/share/nginx/website
      register: web_folder_exists
    - name: Create a directory if it does not exist
      file:
        path: /usr/share/nginx/website
        state: directory
        mode: '0755'
      when: web_folder_exists.stat.exists == False
    - name: Sets Website file
      template:
        src: "templates/website.html.j2"
        dest: "/usr/share/nginx/website/website.html"
      notify: Restart Nginx
    - name: Sets Website vhost
      template:
        src: "templates/default.conf.j2"
        dest: "/etc/nginx/conf.d/default.conf"
      notify: Restart Nginx
  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted